package com.androidarchitecture.db;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import java.util.Map;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testItemDaoConfig;

    private final TestItemDao testItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testItemDaoConfig = daoConfigMap.get(TestItemDao.class).clone();
        testItemDaoConfig.initIdentityScope(type);

        testItemDao = new TestItemDao(testItemDaoConfig, this);

        registerDao(TestItem.class, testItemDao);
    }

    public void clear() {
        testItemDaoConfig.clearIdentityScope();
    }

    public TestItemDao getTestItemDao() {
        return testItemDao;
    }

}
